application: guild-demo-app
version: alpha-001
runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /
   script: main.app
 - url: /bower_components
   static_dir: bower_components


libraries:
- name: webapp2
  version: latest
