runtime: python27
api_version: 1
threadsafe: true

handlers:
 - url: /
   script: main.app
 - url: /bower_components
   static_dir: bower_components
 - url: /add
   script: add.app
 - url: /getall
   script: add.app

libraries:
- name: webapp2
  version: latest
